"""Baseline: the schema as it stood when Alembic was introduced (2026-08-21).

Autogenerated from core/storage/models.py against an empty database. Databases
that predate Alembic (created by the old create_all path, patched by the
one-off tools/_*.py scripts) are STAMPED at this revision by init_db() rather
than re-run through it - see core/storage/db.py.

Revision ID: 0001
Revises:
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_links',
    sa.Column('coach_id', sa.String(length=128), nullable=False),
    sa.Column('player_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('share_reports', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('coach_id', 'player_id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=64), nullable=False),
    sa.Column('game_edition', sa.String(length=32), nullable=False),
    sa.Column('adapter_version', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('capture', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_created_at'), 'matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_matches_game_edition'), 'matches', ['game_edition'], unique=False)
    op.create_index(op.f('ix_matches_game_id'), 'matches', ['game_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sender', sa.String(length=128), nullable=False),
    sa.Column('recipient', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_recipient'), 'messages', ['recipient'], unique=False)
    op.create_index(op.f('ix_messages_sender'), 'messages', ['sender'], unique=False)
    op.create_table('report_feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=48), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_id', name='uq_report_feedback_user_match')
    )
    op.create_index(op.f('ix_report_feedback_match_id'), 'report_feedback', ['match_id'], unique=False)
    op.create_index(op.f('ix_report_feedback_user_id'), 'report_feedback', ['user_id'], unique=False)
    op.create_table('usage_counters',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('matches_analyzed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('auth_subject', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('skill_level', sa.String(length=32), nullable=False),
    sa.Column('control_scheme', sa.String(length=32), nullable=False),
    sa.Column('skill_survey', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coach_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_auth_subject'), 'users', ['auth_subject'], unique=True)
    op.create_table('match_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('game_event_type', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('frame_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_events_category'), 'match_events', ['category'], unique=False)
    op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_events_timestamp_ms'), 'match_events', ['timestamp_ms'], unique=False)
    op.create_table('match_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('higher_is_better', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_metrics_key'), 'match_metrics', ['key'], unique=False)
    op.create_index(op.f('ix_match_metrics_match_id'), 'match_metrics', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_metrics_match_id'), table_name='match_metrics')
    op.drop_index(op.f('ix_match_metrics_key'), table_name='match_metrics')
    op.drop_table('match_metrics')
    op.drop_index(op.f('ix_match_events_timestamp_ms'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_category'), table_name='match_events')
    op.drop_table('match_events')
    op.drop_index(op.f('ix_users_auth_subject'), table_name='users')
    op.drop_table('users')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_report_feedback_user_id'), table_name='report_feedback')
    op.drop_index(op.f('ix_report_feedback_match_id'), table_name='report_feedback')
    op.drop_table('report_feedback')
    op.drop_index(op.f('ix_messages_sender'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_game_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_game_edition'), table_name='matches')
    op.drop_index(op.f('ix_matches_created_at'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('coach_links')
    # ### end Alembic commands ###
